name: Release

on:
  workflow_dispatch: {}
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always
  RUST_TOOLCHAIN: "1.68.0-dev"

jobs:
  release-crate:
    runs-on: ubuntu-latest
    name: Release crate on crates.io
    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v22
      - name: Setup Cachix
        uses: cachix/cachix-action@v12
        with:
          name: saber
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Install Rust nightly
        uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          toolchain: ${{ env.RUST_TOOLCHAIN }}
      - uses: Swatinem/rust-cache@v2
      - name: Publish crates
        run: nix shell .#cargo-workspaces --command cargo workspaces publish --from-git --yes --skip-published --token ${{ secrets.CARGO_PUBLISH_TOKEN }}
